# Generated by Django 4.2.6 on 2023-12-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salgrade',
            name='grade',
            field=models.CharField(max_length=100),
        ),
    ]
